#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

for n_ in {1..100}
do
    if (( n_ % 3 == 0 && n_ % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( n_ % 3 == 0 ))
    then
        echo "Fizz"
    elif (( n_ % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$n_"
    fi
done
