#!/usr/bin/env bash
# Bash script that displays the time for 12 horus and 59 min_s.
#   Displays hour_s from 0 to 12
#   Displays min_s from 1 to 59

hour_=0

while [ $hour_ -le 12 ]
do
  echo "hour_: $hour_"
  min_=1
  while [ $min_ -le 59 ]
  do
    echo "$min_"
    (( min_++ ))
  done
  (( hour_++ ))
done
